name: Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get release tag
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'userbotindo/Anjani'
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'userbotindo/Anjani'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: Anjani ${{ env.VERSION_TAG }}
          draft: true
          prerelease: false
